services: 

  server: 
    build: 
      dockerfile: "./Dockerfile"
    depends_on: 
      - db
    ports: 
      - 3333:3333

  db: 
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: users